### ISSUE TITLE
Drupal 9.1.0 released and use composer to install core

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/ansible-drupal#3]
New version is released, please update to the latest version.

**Comment by chendelin1982** [comment]
Will add the flowing enhancement:

1. Use composer to install Drupal
2. Install [Drush,Drupal Console](https://www.drupal.org/docs/user_guide/en/install-tools.html#s-what-are-command-line-tools)
   ```
    # Install Drush
    composer require drush/drush
    
    # Install Drupal Console
    composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader
   ```

**Comment by qiaofeng1227** [comment]
Transfer to: #4
