### ISSUE TITLE
composer install timeout, role_cloud, role_mysql on AmazonLinux2 

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/ansible-drupal#4]

**Comment by jiaosir-cn** [comment]
Project: Drupal->Apache
Platform: AWS Ubuntu20.04  阿里云 Ubuntu20.04
ip: 54.146.82.72    8.210.0.186
Installation error：

```
TASK [role_common : Check OS support, if not support, exit ansible] ***************************************
fatal: [8.210.0.186]: FAILED! => {"changed": false, "msg": "OS not supported,exit!"}


```
![image](https://user-images.githubusercontent.com/76861519/108579244-03573180-7361-11eb-9d20-83eddf061764.png)

**Comment by jiaosir-cn** [comment]
Project: Drupal->Nginx
Platform: AWS Ubuntu20.04 阿里云 Ubuntu20.04
ip: 54.146.82.72 8.210.0.186
Installation error：
```
TASK [role_common : Check OS support, if not support, exit ansible] ***************************************
fatal: [54.209.215.247]: FAILED! => {"changed": false, "msg": "OS not supported,exit!"}

```
![image](https://user-images.githubusercontent.com/76861519/108579315-4b765400-7361-11eb-99ed-3cbe446580d6.png)

**Comment by jiaosir-cn** [comment]
*********************************************************************************
Project:   Drupal
Platform: 阿里云 AWS Ubuntu20.04 ->Apache&nginx
ip: 54.90.12.251 ，   47.242.218.215 ， 54.89.179.232  ,  8.210.118.193
Installation error：
**********************************************************************************
**Error 1：**   

```
TASK [role_php : Restart PHP-FPM] *************************************************************************
fatal: [54.90.12.251]: FAILED! => {"changed": false, "msg": "Error loading unit file 'php-fpm': org.freedesktop.DBus.Error.FileExists \"Unit php-fpm.service failed to load properly: File exists.\""}

```

![image](https://user-images.githubusercontent.com/76861519/108587083-922d7380-738c-11eb-8b3e-aafa0960c215.png)

**Comment by jiaosir-cn** [comment]
*********************************************************************************
Project: Drupal->Nginx
Platform: 阿里云 Centos7.9
ip: 47.242.223.32
Installation error：
*********************************************************************************
```

```
**Error 1：**

![image](https://user-images.githubusercontent.com/76861519/108580148-2d125780-7365-11eb-8dde-6041655a03c7.png)

**Comment by jiaosir-cn** [comment]
Project: Drupal->Apache&Nginx
Platform: AWS Linux2
ip: 54.237.103.124  54.83.132.144
Installation error：
```
TASK [Use composer install drupal] ************************************************************************
fatal: [54.237.103.124]: FAILED! => {"msg": "Timeout (62s) waiting for privilege escalation prompt: "}
```

**Comment by jiaosir-cn** [comment]
Project: Drupal-Nginx
Platform: AWS Ubuntu20.04
ip: 54.209.215.247
Installation error：
```
TASK [role_mysql : import MySQL apt key] ******************************************************************
fatal: [54.209.215.247]: FAILED! => {"changed": false, "cmd": "/usr/bin/apt-key adv --no-tty --keyserver pgp.mit.edu --recv 5072E1F5", "msg": "Error fetching key 5072E1F5 from keyserver: pgp.mit.edu", "rc": 2, "stderr": "Warning: apt-key output should not be parsed (stdout is not a terminal)\ngpg: keyserver receive failed: No data\n", "stderr_lines": ["Warning: apt-key output should not be parsed (stdout is not a terminal)", "gpg: keyserver receive failed: No data"], "stdout": "Executing: /tmp/apt-key-gpghome.Zh3Vqq866q/gpg.1.sh --no-tty --keyserver pgp.mit.edu --recv 5072E1F5\n", "stdout_lines": ["Executing: /tmp/apt-key-gpghome.Zh3Vqq866q/gpg.1.sh --no-tty --keyserver pgp.mit.edu --recv 5072E1F5"]}
```

```
TASK [role_cloud : AWS Configure] *************************************************************************
fatal: [54.209.215.247]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:GPG error: http://repo.mysql.com/apt/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8C718D3B5072E1F5, E:The repository 'http://repo.mysql.com/apt/ubuntu focal InRelease' is not signed."}

```

**Comment by jiaosir-cn** [comment]
Project: Drupal->Apache 
Platform:阿里云 Centos7.9

Test ok··~

**Comment by qiaofeng1227** [comment]
composer create-project drupal/recommended-project /data/wwwroot/drupal 

Before running composer , clear the cache of composer
```
composer clearcache
```

**Comment by qiaofeng1227** [comment]
Done
